analytics: {}
color:
  brandColors:
    - '#f3f3f2'
    - '#000000'
    - '#960078'
    - '#c883b9'
    - '#666666'
  brandStrength: 0.18581
  lightness: 0.213963
  rhythmicContrast: 0.368243
  saturation: 0.298423
cta: {}
layout_spectrum: 0.452702
name: Michelle S Power
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.37346
