name: Michelle S Power
favicon: null
layout_spectrum: 0.62966
typography_spectrum: 0.37346
title: 'Never Enough Time!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#81a017'
    - '#1779a0'
    - '#515151'
    - '#82b6cb'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
