analytics: {}
color:
  brandColors:
    - '#B0B8C8'
    - '#604818'
    - '#9098A0'
    - '#705830'
    - '#000000'
  brandStrength: 0.88994
  lightness: 0.724099
  rhythmicContrast: 0.706175
  saturation: 0.866997
cta: {}
layout_spectrum: 1
name: Michelle S Power
opengraph: {}
purpose: {}
typography_spectrum: 0.010135
