name: Michelle S Power
favicon: null
layout_spectrum: 0.62966
typography_spectrum: 0.37346
title: 'Never Enough Time! - MP'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f2'
    - '#000000'
    - '#960078'
    - '#c883b9'
    - '#666666'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
