analytics: {}
color:
  brandColors:
    - '#f3f3f2'
    - '#000000'
    - '#960078'
    - '#c883b9'
    - '#666666'
  brandStrength: 0.483953
  lightness: 0.516047
  rhythmicContrast: 0.368243
  saturation: 0.530405
cta: {}
layout_spectrum: 0.070101
name: Michelle S Power
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.030405
