analytics: {}
color:
  brandColors:
    - '#FFFEFF'
    - '#99AAB1'
    - '#131A2A'
    - '#6A7B83'
    - '#02668A'
  brandStrength: 0.483953
  lightness: 0.516047
  rhythmicContrast: 0.368243
  saturation: 0.530405
cta: {}
layout_spectrum: 0.070101
name: Michelle S Power
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.030405
